### ISSUE TITLE
Application Country Download Issues

### ISSUE THREAD

**Issue by zoujiangtao159** [ClaudiuGeorgiu/PlaystoreDownloader#12]
I need to download the application markets of different countries. How do I need to do it? For example, the United States, Taiwan, and Japan. Frequently your country does not allow downloading this situation.

**Comment by ClaudiuGeorgiu** [comment]
I'm sorry, but this tool won't allow you to download apps that are not available in the country from where you are trying to download them. I think you could: 1) use a VPN or 2) rent a server located in the country where you want to download the apps and run this tool there. However, I haven't tried, so these are only suppositions.
