### ISSUE TITLE
I cannot get response from LOGIN_URL

### ISSUE THREAD

**Issue by hustwyk** [ClaudiuGeorgiu/PlaystoreDownloader#14]
When I run the script, the program always blocks when I type 'python3 download.py "com.package.name"', and I can see the debug information: "[DEBUG][urllib3.connectionpool][_new_conn()] Starting new HTTPS connection (1): android.clients.google.com:443". I have checked my network connection and the VPN configuration, and I find no error, I can open Google Play on my chrome browser and download apk in my Pixel. So I wonder what's wrong with my net connection.

**Comment by ClaudiuGeorgiu** [comment]
Actually I never tried using the download script over a VPN so maybe the code needs some adaptation. I just checked and I'm able to download applications so I suspect the error has something to do with VPN usage. Can you check if this simple code works for you (when using the VPN)?

```Python
import requests
print(requests.get('https://android.clients.google.com/').text)
# the output should be a 404 page
```

**Comment by hustwyk** [comment]
> Actually I never tried using the download script over a VPN so maybe the code needs some adaptation. I just checked and I'm able to download applications so I suspect the error has something to do with VPN usage. Can you check if this simple code works for you (when using the VPN)?
> 
> ```python
> import requests
> print(requests.get('https://android.clients.google.com/').text)
> # the output should be a 404 page
> ```

I tried this REQUESTS.GET command under the `Global mode` of my shadowsocks, but I cannot receive any response, then I realize there is something wrong with my SS when I run the python script. So I google the usage of socks in requests function, and I set my proxies in every requests function, then I re-run this script and I download the music apk successfully! Thank you so much.
