### ISSUE TITLE
GUI Gtk

### ISSUE THREAD

**Issue by JimScope** [ClaudiuGeorgiu/PlaystoreDownloader#15]
I could do a graphical interface in Gtk 3, would you agree?

**Comment by ClaudiuGeorgiu** [comment]
Hi, thanks for your interest in this project. I designed this tool to be used mainly through a terminal, but if you can provide a nice looking graphical interface I'll consider it for sure. I never used Gtk before, so this could also be an opportunity for me to learn something new. Thanks!

**Comment by JimScope** [comment]
Ok, great hands to the work, one more question, it is possible to return the url of the application icon. Sorry for my English

**Comment by ClaudiuGeorgiu** [comment]
You should be able to get the icon's url with some code similar to this:

```python
api = Playstore(credentials)
app = api.app_details(package_name).docV2
for image in app.image:
    if image.imageType == 4:
        response = requests.get(image.imageUrl)
        if response.status_code == 200:
            # Save the icon into a file or do whatever you want with it.
            with open('icon.png', 'wb') as f:
                f.write(response.content)
            break
```

**Comment by JimScope** [comment]
I begin to work in https://github.com/JimScope/apkdown is still in alpha and don't download yet mi internet is a shit, contact me lucia.77@nauta.cu when you read this

**Comment by JimScope** [comment]
I begin to work in the GTK+ version. its work but only in retrieve app details, don't download yet because is very dificult to me testing without internet, maybe tomorrow works the download part. Its buggy and is incomplete so don't hurt me. the way for contact me is for email lucia.77@nauta.cu. When you read this, write me for explain the issues with mi jobs environment.

**Comment by JimScope** [comment]
I begin to work in the GTK+ version. its work but only in retrieve app details, don't download yet because is very dificult to me testing without internet, maybe tomorrow works the download part. Its buggy and is incomplete so don't hurt me. the way for contact me is for email lucia.77@nauta.cu. When you read this, write me for explain the issues with mi jobs environment.
