### ISSUE TITLE
Error retrieving information from server. DF-DFERH-01

### ISSUE THREAD

**Issue by unexpectedBy** [ClaudiuGeorgiu/PlaystoreDownloader#18]
root@debian:/home/xxxxxxx/PlaystoreDownloader# python3.7 download.py "com.video.music"
30/09/2019 22:07:24> [ERROR][playstore.playstore.Playstore][app_details()] Error for app "com.video.music": Error retrieving information from server. DF-DFERH-01
30/09/2019 22:07:24> [CRITICAL][__main__][main()] Error when downloading "com.video.music": unable to get app's details

~uname -ans
**Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux**

**Comment by ClaudiuGeorgiu** [comment]
Hi, are you able to download the app by using directly your phone? Apparently my devices are not compatible with this app so if I try to download it I get a different (but expected) error. However, I have already seen `DF-DFERH-01` error in the past but I don't have a solution yet, sorry.

**Comment by unexpectedBy** [comment]
it works now!
