### ISSUE TITLE
there is a error 

### ISSUE THREAD

**Issue by q409640976** [ClaudiuGeorgiu/PlaystoreDownloader#19]
i had modify the config file :credentials.json
but there two error when i run >>>>python3 download.py "com.evozi.deviceid"
and my python is **python3.6**
------------------------------------------------------------------------------
[ERROR][playstore.playstore.Playstore][app_details()] Error for app "mobileSSH.feng.gao": Error retrieving information from server. DF-DFERH-01

 [CRITICAL][__main__][main()] Error when downloading "mobileSSH.feng.gao": unable to get app's details

**Comment by ClaudiuGeorgiu** [comment]
Hi, are you able to download the app by using directly your phone? I was able to download it using my account so I cannot reproduce the issue.

**Comment by q409640976** [comment]
i can download  on my phone,i wan't to know,Where is the mistake?
