### ISSUE TITLE
Anonymous download (without ANDROID ID)

### ISSUE THREAD

**Issue by Symbian9** [ClaudiuGeorgiu/PlaystoreDownloader#20]
> Before interacting with the Play Store you have to provide valid credentials and an ANDROID ID associated to your account.

Is it possible download APKs without `ANDROID ID`? At least *free* apps, such as:

- https://play.google.com/store/apps/details?id=com.hbcavalcanti.oribooklet

**Comment by ClaudiuGeorgiu** [comment]
Hi, I'm not aware of a solution that does not need an `ANDROID ID`. Some applications require particular device capabilities (such as NFC, or ARM support) and the `ANDROID ID` is used to determine if a device has such capabilities.

**Comment by Symbian9** [comment]
> `ANDROID ID` is used to determine if a device has such capabilities.

Is there list of known `ANDROID ID` for popular devices? Such as Xiaomi Redmi 3 Pro ("Ido")

**Comment by ClaudiuGeorgiu** [comment]
As far as I know, the `ANDROID ID` is bound to the Google account and the specific device, and is generated the first time you use the Google account on the device, so it should be unique for every device.
