### ISSUE TITLE
Is it possible to merge split APK apps？

### ISSUE THREAD

**Issue by caiyiyong** [ClaudiuGeorgiu/PlaystoreDownloader#22]
I try to  merge those all into one APK file,but being forced to use a made up signing key means the APK can’t be installed as an update to the genuine app.

Is there maybe an API to get a merged APK include of all the split ones?

**Comment by CaiMiao** [comment]
Use [SAI](https://github.com/Aefyr/SAI/releases) or other compatible methods to install these split apks.

**Comment by yotamgod** [comment]
Another option would be using an older device (I found that when using android 7.x and lower with Oneplus One, I got a single apk instead of split ones).
Granted, I've only played with it a little and there may be other factors in play (user agent, sdk...).

**Comment by david-lev** [comment]
> I try to merge those all into one APK file,but being forced to use a made up signing key means the APK can’t be installed as an update to the genuine app.
> 
> Is there maybe an API to get a merged APK include of all the split ones?

Yes. 
Google Play below version 7.XX does not support splits apk's.
When you register a new GSF ID you must register the Google Play version as an old version and so when you try to download an app, if it has a version consisting of only a single APK file, Google Play will download that version.
Just note that this means that many applications will not be available for the GSF ID you will register.

**Comment by CaiMiao** [comment]
@david-lev see #52 . My gsf id from aurora force me to download full apk and it is up to date.

**Comment by david-lev** [comment]
> @david-lev see #52 . My gsf id from aurora force me to download full apk and it is up to date.

I answered there. #52

**Comment by CaiMiao** [comment]
> if it has a version consisting of only a single APK file, Google Play will download that version.
@david-lev ty for your answer, i understand what you've said, but i just want to disagree your such claim.
it **is** up-to-date.

**Comment by 89z** [comment]
Yes I think @david-lev is wrong as well. It seems you can get either option, depending on the User-Agent. If you have this agent or older, then you get single APK:

~~~
Android-Finsky (sdk=9,versionCode=80919999)
~~~

otherwise you get split.

**Comment by CaiMiao** [comment]
> Yes I think @david-lev is wrong as well. It seems you can get either option, depending on the User-Agent. If you have this agent or older, then you get single APK:
> 
> ```
> Android-Finsky (sdk=9,versionCode=80919999)
> ```
> 
> otherwise you get split.

I don't think it will be merged as it does not download merged anymore for me while [we are older](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/a583a68dfde3bc8a1e45e1b1faa48af5eac49f61/playstoredownloader/playstore/playstore.py#L177) at the moment?

**Comment by CaiMiao** [comment]
> I dont know. I know my tool can download split APK or single APK.

Sorry my bad, i did mess up results from multiple gsfid.

It seems my v7a gsf id does now download split anymore, but my v8a gsf id still downloads split apk for me.  
Maybe I should try your method.

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/165

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/108
