### ISSUE TITLE
Application failed to login after working correctly for one day

### ISSUE THREAD

**Issue by khalsarules16** [ClaudiuGeorgiu/PlaystoreDownloader#23]
Script was working correctly till yesterday. Now it fails to login. Credentials are correct, I can install app on my phone
getting this error:
[WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
09/11/2019 10:01:29> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 2s)
09/11/2019 10:01:31> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 3s)
09/11/2019 10:01:34> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 5s)
09/11/2019 10:01:39> [ERROR][playstore.util][wrapped()] Login failed, please check your credentials (no more retries)
09/11/2019 10:01:39> [CRITICAL][__main__][main()] Error during the download: Login failed, please check your credentials

**Comment by b-reynolds** [comment]
This could be related to #21

**Comment by ClaudiuGeorgiu** [comment]
#24 could help solve this error, please try if you have time.

**Comment by khalsarules16** [comment]
> #24 could help solve this error, please try if you have time.

Working correctly after removing sdk_version. You are awesome :1st_place_medal:   Thanks :+1:
