### ISSUE TITLE
Application Download Failed

### ISSUE THREAD

**Issue by asharif1990** [ClaudiuGeorgiu/PlaystoreDownloader#26]
Hello, I tried to use the script to download apps, but I got the following error:

> [ERROR][playstore.playstore.Playstore][app_details()] Error for app "pdf.tap.scanner": Error retrieving information from server. DF-DFERH-01
18/11/2019 15:20:50> [CRITICAL][__main__][main()] Error when downloading "pdf.tap.scanner": unable to get app's details

can you please help me to solve the following issue. 

thanks in advance 
Amir

**Comment by ClaudiuGeorgiu** [comment]
Hi, I'm sorry but I don't have a solution for this error yet. Sometimes it seems to work by retrying multiple times (see #18).

**Comment by asharif1990** [comment]
Thanks for your answer, 
I checked the #18. I can download the app on the phone, but still I got the error from the server. I will try to check it later.

**Comment by asharif1990** [comment]
solved.

**Comment by caiyiyong** [comment]
> solved.

How did you solve this problem？

**Comment by asharif1990** [comment]
@caiyiyong : In my case, the source of the problem was the device incompatibility with the applications, so I changed my configuration and after that, I was able to download most of the apps that I need, there are still some cases that I still got the same error, but for the most of other cases I am able to download Apps. (I switch into Nexus 5, armx64).
