### ISSUE TITLE
There is a problem about expansion package.

### ISSUE THREAD

**Issue by dolorain** [ClaudiuGeorgiu/PlaystoreDownloader#3]
First , Thank your code , it solve the problem that has plagued me for a long time.

But When i use it , i found a problem about some android app have expansion package.

Like "com.pixonic.wwr"

Besides main apk file, there is a obb file.

When you download it at google play, the obb files will download automatically.

Could you fix it later?

**Comment by ClaudiuGeorgiu** [comment]
Hi, thanks for submitting the issue. I will look into it in the next days and I'll let you know if I manage to implement the `obb` download.

**Comment by ClaudiuGeorgiu** [comment]
With 6cba3f04c13d99b1eafd09cf9cc6b0c2a0fe5ff9 the additional files should be downloaded in the same directory as the `apk` file, please try it and let me know if it works as intended.

**Comment by dolorain** [comment]
Many thanks.
I do have tested your program.
It went perfectly.

And i have read your code.
It was beautiful.
But i think if the Google Open API's response have the obb file name , you shouldn't change the name.
Because the obb file will save as path : "android:root/obb/... " the obb file name have a rule like : 
 "com.pixonic.wwr.apk"
 "com.pixonic.wwr.obb"
If break the rule , the main apk you installed will not work. like the main apk cant find the expansion file.

And a little suggestion , the program cant set the saving name of obb file , Maybe you should find a way
to download with custom the obb's file name.
And some one told me , the expansion files, they do have a another filename extension ".data", the 
".data" file save as path "android:root/data/...".
But i haven't found a package like this .

After all. Thanks for your code , It's really solve the problems.

**Comment by ClaudiuGeorgiu** [comment]
Thanks for the feedback, I'll look more into this when I have time.
- [ ] Fix the `obb` file renaming
- [ ] Let the user choose the name for the additional downloaded files

**Comment by dolorain** [comment]
ok,it worked perfectly.

**Comment by ClaudiuGeorgiu** [comment]
The official [Android Developer page](https://developer.android.com/google/play/expansion-files.html#Filename) describes the naming convention for the `obb` files, so I'm going to implement that. I could also add `--main-obb-name` and `--patch-obb-name` optional parameters to let the user specify different names to use for the additional files, but I'm not sure if this can be useful since there already exists an official naming convention. What do you think @dolorain?

**Comment by dolorain** [comment]
i couldn't find a better way to finalized the file name, so i totally agree your idea.

**Comment by dolorain** [comment]
this issue should be closed.
