### ISSUE TITLE
how to unlock download limitation ?

### ISSUE THREAD

**Issue by yonited** [ClaudiuGeorgiu/PlaystoreDownloader#30]
we are building a website based on your API ... when we try to download more than three apps/games in the same time the API stop working ... also download speed not that good ... is there any way around these issues  

Thank you

**Comment by ClaudiuGeorgiu** [comment]
Hi, this tool is not intended for multiple downloads at the same time. I don't know if/how you can bypass this limitation, when I have to download multiple applications I just keep the request rate low enough not to be blocked by Google's servers.
