### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by tejas619** [ClaudiuGeorgiu/PlaystoreDownloader#31]
While running download.py I am getting the following error: 
```OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38m-darwin.so': dlopen(/Users/tkhairnar/Documents/PlaystoreDownloader/venv/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-38m-darwin.so, 6): image not found, Trying '_raw_ecb.abi3.so': dlopen(/Users/tkhairnar/Documents/PlaystoreDownloader/venv/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 6): image not found, Trying '_raw_ecb.so': dlopen(/Users/tkhairnar/Documents/PlaystoreDownloader/venv/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.so, 6): image not found```

I followed the installation process and running python3.8.
Can you help me?

**Comment by ClaudiuGeorgiu** [comment]
Hi, I've never seen that error before. From your logs, it looks like you're using macOS, can you provide the exact version? I've tried the tool only on Windows 10 and Ubuntu, but maybe I can try adding some automatic CI tests also for macOS. It looks like an error with the `pycryptodome` package, but at the moment I'm not able to replicate.

**Comment by tejas619** [comment]
The version of MacOS i am trying to run on is macOS Catalina v10.15.3

**Comment by ClaudiuGeorgiu** [comment]
I tried on macOS 10.15 using GitHub actions, but I cannot replicate the error.
