### ISSUE TITLE
version of apk file

### ISSUE THREAD

**Issue by 7c** [ClaudiuGeorgiu/PlaystoreDownloader#33]
Is there a way to name the apks by version? We are archiving apk files by version number for clients from china. So version number as part of the output filename would be really neat. Basically if we put this to crontab, even we do not know the version without looking up to web.

**Comment by ClaudiuGeorgiu** [comment]
Hi, you can add the version to the name of the saved file. First you need to save the version by modifying this dictionary (add the following 2 lines): https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/efcefa2de8b77633710fc31dcea6157b212ddfe1/download.py#L97-L101
```Python
"versionString": app.details.appDetails.versionString,
"versionCode": app.details.appDetails.versionCode,
```
Then you can change this code to include the version in the name:
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/efcefa2de8b77633710fc31dcea6157b212ddfe1/download.py#L111-L113
```Python
"{0} by {1} - {2} - v. {3}.apk".format(
    details["title"], details["creator"], details["package_name"] , details["versionString"]
),
```
