### ISSUE TITLE
The Play Store application on your device is outdated and does not support this purchase

### ISSUE THREAD

**Issue by IslandJohn** [ClaudiuGeorgiu/PlaystoreDownloader#36]
I've been using an APK extractor to side-load apps from my phone to devices that are listed as incompatible with a given app (e.g. Minecraft). This stopped working with the latest MCPE version (extracted APK installs but crashes on startup). I noticed that the extracted APK size is much less than what is shown during app download, so I tried to download it using this project. However, I get the following error:

21/04/2020 23:57:19> [INFO][engineio.server][send()] 39d673f13904464da1e2e9e2c080fe65: Sending packet OPEN data {'sid': '39d673f13904464da1e2e9e2c080fe65', 'upgrades': [], 'pingTimeout': 600000, 'pingInterval': 25000}

21/04/2020 23:57:19> [INFO][engineio.server][send()] 39d673f13904464da1e2e9e2c080fe65: Sending packet MESSAGE data 0

21/04/2020 23:57:31> [INFO][engineio.server][receive()] 39d673f13904464da1e2e9e2c080fe65: Received packet MESSAGE data 2["start_download","com.mojang.minecraftpe"]

21/04/2020 23:57:31> [INFO][socketio.server][_handle_event()] received event "start_download" from 39d673f13904464da1e2e9e2c080fe65 [/]

21/04/2020 23:57:32> [ERROR][playstore.playstore.Playstore][_handle_missing_payload()] Error for app 'com.mojang.minecraftpe': The Play Store application on your device is outdated and does not support this purchase.

21/04/2020 23:57:32> [INFO][socketio.server][emit()] emitting event "download_error" to 39d673f13904464da1e2e9e2c080fe65 [/]

21/04/2020 23:57:32> [INFO][engineio.server][send()] 39d673f13904464da1e2e9e2c080fe65: Sending packet MESSAGE data 2["download_error","Error for app 'com.mojang.minecraftpe': The Play Store application on your device is outdated and does not support this purchase."]

Any thoughts on this problem?

**Comment by ClaudiuGeorgiu** [comment]
Hi, can you try with latest commit on `develop` branch 7be39bfe43a0571fc4308edef537bc1c071b20e5?

**Comment by IslandJohn** [comment]
Different error:

23/04/2020 00:48:51> [INFO][engineio.server][send()] 2734a5c848084480bae8fc25f18033f2: Sending packet OPEN data {'sid': '2734a5c848084480bae8fc25f18033f2', 'upgrades': [], 'pingTimeout': 600000, 'pingInterval': 25000}
23/04/2020 00:48:51> [INFO][engineio.server][send()] 2734a5c848084480bae8fc25f18033f2: Sending packet MESSAGE data 0
23/04/2020 00:49:00> [INFO][engineio.server][receive()] 2734a5c848084480bae8fc25f18033f2: Received packet MESSAGE data 2["start_download","com.mojang.minecraftpe"]
23/04/2020 00:49:00> [INFO][socketio.server][_handle_event()] received event "start_download" from 2734a5c848084480bae8fc25f18033f2 [/]
23/04/2020 00:49:01> [ERROR][playstore.playstore.Playstore][_handle_missing_payload()] Error for app 'com.mojang.minecraftpe': Can't install. Please try again later.
23/04/2020 00:49:01> [INFO][socketio.server][emit()] emitting event "download_error" to 2734a5c848084480bae8fc25f18033f2 [/]
23/04/2020 00:49:01> [INFO][engineio.server][send()] 2734a5c848084480bae8fc25f18033f2: Sending packet MESSAGE data 2["download_error","Error for app 'com.mojang.minecraftpe': Can't install. Please try again later."]

**Comment by ClaudiuGeorgiu** [comment]
I get the same error, but I didn't purchase the application so I thought that was the reason. Do you have other paid applications on your account? If yes, are you able to download them by using the tool?

**Comment by IslandJohn** [comment]
It's a purchased app, tried something else, same error.

**Comment by ClaudiuGeorgiu** [comment]
I purchased the app to test if the error persists, but now I'm able to download it without problems, so the code is working (at least in my case). I'm also able to download the other apps I purchased so I cannot replicate the error, sorry.

**Comment by IslandJohn** [comment]
My bad... I was using the wrong GSF ID. It works, but I'll open a separate issue.
