### ISSUE TITLE
Only the base APK is downloaded when the app is deployed as an App Bundle

### ISSUE THREAD

**Issue by IslandJohn** [ClaudiuGeorgiu/PlaystoreDownloader#38]
Some Android apps are now distributed as an [App Bundle](https://developer.android.com/platform/technology/app-bundle), composed of multiple device-centric APKs. This means in order for them to work, you need all the components, not just the base APK. This project only downloads the base APK.

**Comment by ClaudiuGeorgiu** [comment]
In the [available parameters](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader#available-parameters) you have the option `-s` and `-b` to download the additional files, is any file missing after downloading with these parameters?

**Comment by IslandJohn** [comment]
I should have RTFM, sorry... It worked mostly. It downloaded the the files, but included only the x86 architecture requirement (not arm64). Is the architecture being downloaded tied to the GSF ID?

**Comment by ClaudiuGeorgiu** [comment]
> Is the architecture being downloaded tied to the GSF ID?

Yes, when you download an application it's like downloading it with your device, so the same limitations apply.
