### ISSUE TITLE
Error retrieving information from server. DF-DFERH-01

### ISSUE THREAD

**Issue by pich4ya** [ClaudiuGeorgiu/PlaystoreDownloader#39]
I have configured the credentials.json with valid user and device ID, enabled the "less secure app" option. However, I always get this error message upon downloading any app.

I tried to change LANG_CODE and LANG but no luck. The account does not bind with any 2FA.

```$ python3 download.py "com.google.android.gms"
15/05/2020 15:19:55> [ERROR][playstore.playstore.Playstore][app_details()] Error for app 'com.google.android.gms': Error retrieving information from server. DF-DFERH-01
15/05/2020 15:19:55> [CRITICAL][__main__][main()] Error when downloading 'com.google.android.gms': unable to get app's details
```

**Comment by ClaudiuGeorgiu** [comment]
Hi, other users had the same issue (#18, #26) but unfortunately I don't have a solution yet. I also get this error sometimes but usually for me it's enough to retry a couple of times for the download to work.

**Comment by Bonjur** [comment]
same error again and again

**Comment by dpsrc** [comment]
I see the same issue all the time for any apk name with the ids of all my devices and re-tried many times, but it never made it get downloaded.

**Comment by colincowie** [comment]
same issue

**Comment by dimon222** [comment]
Seems to happen when login GSF id doesn't match to one that is tied to credentials (don't use Android ID, use the GSF id!).
The instruction with emulating device or using device with necessary model is absolutely required to get GSF id recognized by google and bound to account (until you change your password that will disband it again).

**Comment by Zeik0s** [comment]
@dimon222 solution worked for me (choosing the GSF ID instead of the Android Device ID shown in the Device ID App)

**Comment by david-lev** [comment]
You need to login into your google account through webbrowser and confirm that failed login attemp (“That was me”) in the activity log.

**Comment by dimon222** [comment]
Whoever started randomly suffering from this again (worked but stopped working) - you need to relogin again to account with your device that uses GCF (virtual or real), google randomly resets tokens and if those got reset - the device gets untied from account, so GCF is not being recognized while logging in.

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> googleplay -a com.google.android.gms
Title: Google Play services
UploadDate: Feb 14, 2022
VersionString: 22.02.21 (100700-428111784)
VersionCode: 220221031
NumDownloads: 13.726 B
Size: 99.621 MB
Offer: 0.00 USD
~~~

https://github.com/89z/googleplay
