### ISSUE TITLE
Dear ClaudiuGeorigiu！About download country

### ISSUE THREAD

**Issue by MrLuoXuan** [ClaudiuGeorgiu/PlaystoreDownloader#41]
How did we exactly know what country can download the app when we meet follow problem.

buy app failed Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.

Is there any interface will tell us what country can download the app?

**Comment by ClaudiuGeorgiu** [comment]
Hi, I don't know if the country information is available somewhere. In such case I would visit the Play Store page looking for hints (e.g. in the description of the app, if the application is bound to a specific region, probably the description will be available only in a specific language).

**Comment by MrLuoXuan** [comment]
> Hi, I don't know if the country information is available somewhere. In such case I would visit the Play Store page looking for hints (e.g. in the description of the app, if the application is bound to a specific region, probably the description will be available only in a specific language).

Ok, thank you very much !
