### ISSUE TITLE
I did everything to make it works but it gives me failed login!

### ISSUE THREAD

**Issue by haythama** [ClaudiuGeorgiu/PlaystoreDownloader#43]
I've tried everything to make it works, My username and password are correct, no Gmail security, enabled everything to make it works, copied the android device id, downloaded applications using this account, and no success. 

tried to print the error and failed! 
08/11/2020 11:20:52> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
08/11/2020 11:20:53> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 2s)

**Comment by haythama** [comment]
why there is no reply?!

**Comment by ClaudiuGeorgiu** [comment]
Sorry but I don't have anything else to suggest, the above steps (that you already tried) should solve most issues, but since I cannot replicate the error I can't help, sorry.

**Comment by falcon1996** [comment]
Same is the case on my setup, it gives:
[WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
24/11/2020 01:49:30> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 2s)
24/11/2020 01:49:32> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 3s)
24/11/2020 01:49:36> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 5s)

**Comment by dsevcik** [comment]
We had same problem and we find out that this problem probably occurs while using python interpreter together with clang (basically on mac machines). when the tool is ran with python together with gcc, it works properly.

**Comment by haythama** [comment]
So how to solve the issue? 
Playstore Downloader will make my life easier!!

**Comment by ClaudiuGeorgiu** [comment]
These actions *might* help:

* try using the [Docker version](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/tree/c35f8bc101b1e7f4f1ef32e3227b0cf62723ee9d#docker-image)

* try with a different version of Python (e.g., if you were using 3.7, try with 3.9)

* try different cipher combinations https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/c35f8bc101b1e7f4f1ef32e3227b0cf62723ee9d/playstore/playstore.py#L20-L34

**Comment by gdraperi** [comment]
I wonder if the GOOGLE_PUB_KEY has not changed? Can you tell how you retrieved it so I can check if it has changed? 

Thanks a lot for this really helpful tool.

**Comment by psimecek-wandera** [comment]
For me the problem has been solved by this commit:
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/commit/f5321177af2f456122b4c2fa46fbb29c510be688#diff-75dbff5b6f417f3775664486a325345a27e2f5bb2a05d31f631fa5143a59effc

that removed requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS overrides on MacOS machines.

**Comment by Error0x0001** [comment]
Hi,

Dont forget to temporarily unlock access to your account (https://accounts.google.com/DisplayUnlockCaptcha)
in my case that was the problem!

Make sure you are logged in using the same Gmail account in same machine (same IP Address)
This will allow access to your Google account for about 10 minutes,

**Comment by yotamgod** [comment]
Anyone find a way around this?

I'm running into an issue where everything works fine from my local Ubuntu, however (since March 8th) when running from an Ubuntu Server (different IP, yes), I get the dreaded UNKNOWN_ERR. 
Like @Error0x0001 said, accessing the https://accounts.google.com/DisplayUnlockCaptcha url, fixes the error for about 10 minutes but requires intervention.

I've tried:
1. 2 versions of Python (3.6, 3.8)
2. Signing into the Play Store from my remote machine
3. Switching the remote machine IP
4. Changing urllib3 version (where ciphers are specified)

From snooping around other Google Play downloaders (matlink, and some node versions), I haven't been able to find notice of this..

**Comment by ClaudiuGeorgiu** [comment]
Hi @yotamgod, are you using 2-Step Verification for your account? I've noticed that since using 2-Step Verification, I usually don't get login errors when using the same account on different servers.

**Comment by yotamgod** [comment]
Hey @ClaudiuGeorgiu, I'm not currently using 2FA and am open to try. 
However, considering my usage is an "automatic download server", wouldn't 2-Step Verification require manual intervention on each login? (meaning I would need to approve the login on my phone/email every time a request to download an app occurs)

By the way, I'm guessing my next move will be creating a new gmail account and logging the devices in through said server, however I'm leaving that as kind of a last resort.

**Comment by ClaudiuGeorgiu** [comment]
> However, considering my usage is an "automatic download server", wouldn't 2-Step Verification require manual intervention on each login?

When using 2FA, you will need to generate an [App Password](https://support.google.com/accounts/answer/185833) for the `PASSWORD` field (instead of using your actual password), so no manual intervention will be needed. However, I cannot guarantee that this solution will also work for you, I know only that it worked for me.

**Comment by yotamgod** [comment]
I think I might be in love with you @ClaudiuGeorgiu
It actually seems to be working! I'll keep updating in case any issues arise.

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/49
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/57

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/52

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/61
