### ISSUE TITLE
_execute_request() dynamic user-agent

### ISSUE THREAD

**Issue by yotamgod** [ClaudiuGeorgiu/PlaystoreDownloader#44]
Hello,
From what [I've read](https://raccoon.onyxbits.de/dummydroid-v2/google-play-device-compatibility/#understanding-google-play-device-compatibility), the useragent of a request to Google Play can have an affect on the ability of a device to download an app. 
And so, I was wondering what the reasoning behind the static user-agent used in the `_execute_request()` method (was this taken into consideration, or is it just impossible to do without the devices specifications?).
Great library!

**Comment by ClaudiuGeorgiu** [comment]
Hi, the user agent is of course important and is taken into consideration during the download. When I started this project (3 years ago) I couldn't find a way to generate the user agent dynamically so I decided to use a static one that just works (mostly). It might be not the best solution but it works pretty well for my use case so, at least for now, I'm happy with this solution.
