### ISSUE TITLE
Splitting the download function

### ISSUE THREAD

**Issue by yotamgod** [ClaudiuGeorgiu/PlaystoreDownloader#45]
Hey Claudiu, 
I has wondering if there are any plans on splitting the `_download_with_progress` method into the different parts it includes (details, purchase, delivery..) to allow for more modular usage of the project (for example, I need to edit the update section, but would still want to easily merge in future changes).
Again, I really love the project.
Thanks

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently I have no future plans regarding the download method, but I'm open to discussion if you want to propose some enhancements.
