### ISSUE TITLE
Wrong code inputted? "Login failed, please check your credentials" error persists.

### ISSUE THREAD

**Issue by TheoDrHashiriya** [ClaudiuGeorgiu/PlaystoreDownloader#46]
Disabled all security features including 2-Step Verification. 

Working directory: 
/C/Source/credentialsfolder or C:\Source\credentialsfolder
Note: credentialsfolder already contains the .json file and the output folder.

Code inputs tried: 
$ winpty docker run \
    -u $(id -u):$(id -g) \
    -v "${PWD}/credentials.json":"/app/credentials.json" \
    -v "${PWD}/output/":"/app/Downloads/" \
    --rm -it downloader "net.zedge.android"

&

$ winpty docker run \
   -v "/c/Source/credentialsfolder/credentials.json":"/app/credentials.json" \
   -v "/c/Source/credentialsfolder/output/":"/app/Downloads/" \
   --rm -it downloader "net.zedge.android"

# I assume it's the input's fault and not the credentials.json file. Would you suggest a way of how I could type it, or give an input that works?

![Screenshot (68)](https://user-images.githubusercontent.com/74580203/99343531-102f3980-28c9-11eb-9368-f13accd95475.png)

# Note: I don't know why, but these codes put these odd files and folders in the credentialsfolder.

**Comment by ClaudiuGeorgiu** [comment]
Hi, sorry but I never used docker on windows so I can't help with this.
