### ISSUE TITLE
Download apk which is available only for a specific country

### ISSUE THREAD

**Issue by TempleOfHorus** [ClaudiuGeorgiu/PlaystoreDownloader#47]
Is it possible to download apk which is available only for a specific country ?
Example (for Philippines):
https://play.google.com/store/apps/details?id=com.squareenix.oko&hl=en&gl=ph

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently it's not possible. See https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/12#issuecomment-385961105.

**Comment by TempleOfHorus** [comment]
Amazing! Thank you.

**Comment by TempleOfHorus** [comment]
I tried to download it using a VPN and it works. However you need to login into google api from the country you have created account. So I added to your program code: input(''). Then I logged into google api. While program was waiting on input, I turned on my VPN, pressed enter and program continued and found/downloaded APK.

Cheers.

**Comment by TempleOfHorus** [comment]
I tried to download it using a VPN and it works. However you need to login into google api from the country you have created account. So I added to your program code: input (''). Then I logged into google api. While program was waiting on input, I turned on my VPN, pressed enter and program continued and found / downloaded APK.

Cheers.

**Comment by ClaudiuGeorgiu** [comment]
Thanks for the update @TempleOfHorus!
