### ISSUE TITLE
 Login failed, please check your credentials

### ISSUE THREAD

**Issue by theapache64** [ClaudiuGeorgiu/PlaystoreDownloader#49]
### Prerequisites

Before opening this issue, I tried the following steps:

* [x] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader#-installation) and configured the [account/credentials](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader#-configuration)

* [x] Made sure the download works when using the same account on a real device/emulator

* [x] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/PlaystoreDownloader)

### Description

I've done the setup as instructed (install from source) but am getting `Login failed, please check your credentials`

### Steps to reproduce

1.  Install from source
2.  Setup `credentials.json`
3.  execute below command

```
pipenv run python download.py "com.theapache64.papercop"
```

**Expected behavior:**

```
APK Downloaded
```

**Actual behavior:**

```
~/Desktop/Untitled Folder 6/PlaystoreDownloader$ pipenv run python download.py "com.theapache64.papercop"
29/01/2021 07:14:32> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
29/01/2021 07:14:34> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 2s)
29/01/2021 07:14:36> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 3s)
29/01/2021 07:14:39> [WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 5s)
29/01/2021 07:14:44> [ERROR][playstore.util][wrapped()] Login failed, please check your credentials (no more retries)
29/01/2021 07:14:44> [CRITICAL][__main__][main()] Error during the download: Login failed, please check your credentials
```

### Versions

* **Installation mode** (e.g., from source or with Docker): Source
* **PlaystoreDownloader version** (e.g., commit c35f8bc): 4a18844a497c0e843986b89de3f7667a234aca49
* **OS** (e.g., Ubuntu 18.04): Ubuntu 16.04
* **Python version** (e.g., 3.8.6): Python 3.6.12 (default, Aug 18 2020, 02:08:22)

**Comment by ClaudiuGeorgiu** [comment]
Hi, please see https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43#issuecomment-736022754. Sorry, but currently I don't have other suggestions.

**Comment by Tobyyyyyyyyyy** [comment]
- Python version request `v3.9.1`
`pipenv install --python 3.9.1`
- Account password can see [#43 issuecomment](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43#issuecomment-801074081)
- `gsfId`(`ANDROID_ID`) can use [Aurora Store](https://auroraoss.com/)
location: `/data/data/com.aurora.store/shared_prefs/com.aurora.store_preferences.xml`

Hope it work to you.

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43

https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/49
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/57
