### ISSUE TITLE
Split APK advanced problem

### ISSUE THREAD

**Issue by CaiMiao** [ClaudiuGeorgiu/PlaystoreDownloader#52]
Hi,

I'm using your tool (running 4a18844 from source) to automatically grab APKs for an app in different architecture (`arm64-v8a` and `armeabi-v7a`).
I recently found my GSF ID for `v8a` unable to login anymore, so I switched the GSF ID to a newly generated one, and the ID was generated by [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore).

When I try to download the app (that should be delivered in base/split APKs, formally known as App Bundle) with your `-s` param,  
it downloaded a **merged**(non-A/B, but still single architecture) apk instead, which is a suprising but unexpected behavior:  
I did wanted to download merged apk, but still I want to preserve the ability to download A/B apk as well.  
I'm getting ability to download a merged APK, but meanwhile I'm losing ability to download A/B format apks.

But with the same GSF ID I **am able** to download A/B apk from Aurora Store without problem.

I also generated a new GSF ID for the `v7a`, through your tool the new ID downloads merged APK for me, and the old ID still downloads A/B APKs like before.

I believe there may be some option for the Playstore API - with the same (`v8a`) ID I can download merged APK from your tool and A/B from Aurora Store.  
If you can figure out what is the difference and make both type of APK available to download, that would be a great help.

Additionally if you can implement a "check" ability to check against if an app is available in A/B or not, it will be even better so I can skip a few redunant steps in my custom setup on demand.

I can provide both of my `v7a` GSF ID for you if needed.

A big thank you for you great work.

**Comment by ClaudiuGeorgiu** [comment]
Hi @CaiMiao, thanks for the detailed report. Currently the `-s` flag is not working as intended also for me (I added a note in the README), I have looked at this issue in the past but I haven't been able to find a solution. Maybe I'll look into it again in the future if I have time, but I can't promise anything.

**Comment by david-lev** [comment]
As you probably know, the GSF ID is connected to a datasheet that created and uploaded automatically when you adding Google account to a device. This datasheet contains info about the device, so Google Play You can tailor your apps for you or prevent you from downloading apps that are not supported on your device.
Among other things, the information includes the specifications on the hardware, resolution, cpu, supported languages, features, as well as the versions of Google Play and the GMS. 

To the best of my knowledge, the reason splits can't be downloaded is because of the Google Play version (com.android.vending) that existed at the time of the GSF ID registration.

This can happen even in new gsf id registrations and the only solution is to to register a new one but with updated play store app.

**Comment by CaiMiao** [comment]
I newly generated a gsfid and it seems working with split apks now,

but meanwhile i will lose access to download full apk once the old gsfid expired....

**Comment by fleetof** [comment]
Hi @CaiMiao, thanks for sharing. Can you tell me how to get the GSF ID through Aurora store? And how to fill in the email and password in the configuration file after obtaining GSF ID?

**Comment by CaiMiao** [comment]
> Hi @CaiMiao, thanks for sharing. Can you tell me how to get the GSF ID through Aurora store? And how to fill in the email and password in the configuration file after obtaining GSF ID?

register a new google account, use it to login aurora store within a rooted phone/emulator, then explore the `shared_prefs/` in `/data/data`

**Comment by 89z** [comment]
@CaiMiao how did you avoid the login problems? I tried using this tool, but I could never get it to work

**Comment by CaiMiao** [comment]
> @CaiMiao how did you avoid the login problems? I tried using this tool, but I could never get it to work

I followed those steps provided in readme, but it seems sometimes working, sometimes not.

**Comment by 89z** [comment]
@CaiMiao OK I got the login working, but it seems that `-s` gives the same result as not using it. I tried with `com.google.android.youtube`. Do you have an example app to demonstrate the issue?

**Comment by 89z** [comment]
I get same result with `com.tencent.mm`, regardless of `-s` option
