### ISSUE TITLE
Auth broken

### ISSUE THREAD

**Issue by morethanhater** [ClaudiuGeorgiu/PlaystoreDownloader#57]
It seems, like authentication is broken because of google auth scheme has completely changed
Script worked perfect untill a few days, when scheme were completely changed.
I found more info about it at this issue: 
https://github.com/onyxbits/raccoon4/issues/95

**Comment by needsomesl33p** [comment]
I can confirm it. I could login using a browser, but the script could not login with the same credentials.

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/49

https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/57
