### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by mrjk990** [ClaudiuGeorgiu/PlaystoreDownloader#6]
```
root@ubuntu:~/PlaystoreDownloader# python3 download.py "com.whatsapp"
Traceback (most recent call last):
  File "download.py", line 9, in <module>
    from playstore.playstore import Playstore
  File "/root/PlaystoreDownloader/playstore/playstore.py", line 9, in <module>
    import requests
ImportError: No module named 'requests'
root@ubuntu:~/PlaystoreDownloader# python3 download.py "com.facebook"
Traceback (most recent call last):
  File "download.py", line 9, in <module>
    from playstore.playstore import Playstore
  File "/root/PlaystoreDownloader/playstore/playstore.py", line 9, in <module>
    import requests
ImportError: No module named 'requests'
root@ubuntu:~/PlaystoreDownloader#
```

**Comment by ClaudiuGeorgiu** [comment]
Hi, did you install the requirements `pip3 install -r requirements.txt`? It looks like a package wasn't installed correctly, did you follow all the instructions contained in the readme? Thanks.

**Comment by mrjk990** [comment]
it work now , thanks ,
but i have problem with login 
`root@ubuntu:~/PlaystoreDownloader# python3 download.py "com.facebook.lite"
29/10/2017 14:08:59> [CRITICAL][_login()] Login failed. Please check your credentials.`

login details is correct and `Allow less secure apps: ON` :(

**Comment by ClaudiuGeorgiu** [comment]
In order to avoid the download of the additional files you have to remove/comment this section from `playstore/playstore.py`:
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/b0cea41f9d676279685bb66e6dca1401a830ed44/playstore/playstore.py#L404-L435

I will add a command line argument to make the additional files download optional, thanks for the suggestion.

**Comment by mrjk990** [comment]
thanks allot , i am waiting new update :+1:
