### ISSUE TITLE
Cannot download apk

### ISSUE THREAD

**Issue by artem469** [ClaudiuGeorgiu/PlaystoreDownloader#60]
I tried to download apk and get error message: Error retrieving information from server. DF-DFERH-01
What does it mean?

### Versions

Installation mode - from source 
PlaystoreDownloader version 1.3.0
MacOS BigSur
Python 3.9.7

**Comment by ClaudiuGeorgiu** [comment]
Hi, it's a known issue but I don't have a solution yet (please see #39 for more information).
