### ISSUE TITLE
pipenv install --deploy not working?

### ISSUE THREAD

**Issue by gl6692** [ClaudiuGeorgiu/PlaystoreDownloader#68]
When I run pipenv install --deploy I get this and the script exists:

Installing dependencies from Pipfile.lock (75783e)...
  ================================ 0/0 - 00:00:00

I am located in the correct folder. Python 3.10.0.

**Comment by gl6692** [comment]
I have managed to run this with python 3.8.5.

I am using App Password from Google, and when I try to run py -m playstoredownloader.cli -b -s "com.adobe.lrmobile", I get:

C:\websites\sooftware\adminnew\updatechecker\automaticandroid\PlayStoreDownloade
r_new\PlaystoreDownloader>py -m playstoredownloader.cli -b -s "com.adobe.lrmobil
e"
04/11/2021 12:45:55> [ERROR][playstoredownloader.playstore.playstore.Playstore][
download()] Error during the download: list index out of range
Traceback (most recent call last):
  File "...\playstoredownloader\playstore\playstore.py", l
ine 669, in download
    list(
  File "...\playstoredownloader\playstore\playstore.py", l
ine 328, in _download_with_progress
    offer_type = meta.docV2.offer[0].offerType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\sit
e-packages\google\protobuf\internal\containers.py", line 208, in __getitem__
    return self._values[key]
IndexError: list index out of range
04/11/2021 12:45:55> [ERROR][playstoredownloader.downloader.multi_downloader][do
wnload()] There was an error when downloading package com.adobe.lrmobile
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\run
py.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\run
py.py", line 87, in _run_code
    exec(code, run_globals)
  File "...\playstoredownloader\cli\__main__.py", line 5,
in <module>
    cli()
  File "...\playstoredownloader\cli\cli.py", line 8, in cl
i
    main(**vars(get_cmd_args()))
  File "...\playstoredownloader\downloader\main.py", line
25, in main
    return download_packages(package, blobs, split_apks, credentials, out_dir, t
ag)
  File "...\playstoredownloader\downloader\main.py", line
30, in download_packages
    return MultiDownloader(packages, downloader).download()
  File "...\playstoredownloader\downloader\multi_downloade
r.py", line 26, in download
    raise DownloadError()
playstoredownloader.downloader.downloader.DownloadError

C:\websites\sooftware\adminnew\updatechecker\automaticandroid\PlayStoreDownloade
r_new\PlaystoreDownloader>

**Comment by ClaudiuGeorgiu** [comment]
Do you get the same error with every app?

**Comment by gl6692** [comment]
Tried with a few other apps, same error.

**Comment by ClaudiuGeorgiu** [comment]
> Tried with a few other apps, same error.

I can't replicate the error with my account, sorry.
