### ISSUE TITLE
problem when call from php

### ISSUE THREAD

**Issue by mrjk990** [ClaudiuGeorgiu/PlaystoreDownloader#7]
`<?php
	$id ="com.whatsapp";
	$cmd = 'python3 ./PlaystoreDownloader/download.py "'.$id.'" 2>&1';
	$output = shell_exec($cmd);
	var_dump($output);
`

output 

`string(873) "01/11/2017 23:07:52> [CRITICAL][_load_configuration()] Missing configuration file.
Traceback (most recent call last):
  File "/var/www/html/PlaystoreDownloader/playstore/playstore.py", line 40, in __init__
    self._load_configuration(config_file)
  File "/var/www/html/PlaystoreDownloader/playstore/playstore.py", line 74, in _load_configuration
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./PlaystoreDownloader/download.py", line 80, in 
    main()
  File "./PlaystoreDownloader/download.py", line 42, in main
    api = Playstore(args.credentials.strip(' \'"'))
  File "/var/www/html/PlaystoreDownloader/playstore/playstore.py", line 52, in __init__
    except json.decoder.JSONDecodeError as ex:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
"`
what the problem ?! i need to use it on webserver :(

are you can make python file to call download.py from webserver.
example "index.py?id=com.whatsapp" output json code
`{"status":"completed","file":"\/com.whatsapp.apk","file_size":"30061 KB"}`

and please add message "completed" after download finished

**Comment by ClaudiuGeorgiu** [comment]
You should try specifying the credentials path:
```
python3 ./PlaystoreDownloader/download.py -c ./PlaystoreDownloader/credentials.json "com.example.app"
```
Otherwise change the working directory before calling the script:
```
cd ./PlaystoreDownloader/
python3 download.py "com.example.app"
```
In order to modify the returned message after the download just modify the following lines:
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/a19fe932aa06aceff83ef6c80b750167e123b286/download.py#L88-L90
to something like:
```
if success:
    return 'place here success json'
else:
    return 'place here failure json'
```

**Comment by mrjk990** [comment]
thank you @ClaudiuGeorgiu  it's work fine :D
