### ISSUE TITLE
Can't install apk files downloaded by PlaystoreDownloader

### ISSUE THREAD

**Issue by Nicopotame** [ClaudiuGeorgiu/PlaystoreDownloader#71]
Hi, 

I can't install apk files downloaded by PlaystoreDownloader.
I'm on an android 11, and when installing the apk, an error occured : "application not installed".
Could you send me some ideas of what can I do to fix this issue please ?
I search on the internet without results for now...

Thanks in advance !

Kind regards

**Comment by 89z** [comment]
is it a single APK or split

**Comment by ClaudiuGeorgiu** [comment]
Hi @Nicopotame, can you provide the package names of the apps that you can't install?

**Comment by Nicopotame** [comment]
Hi,

Thanks for this fast answer !
I tried a lot of apk, all of them failed on the installation. I tried on 2 different devices.
For example, there is : com.adobe.reader.apk 
I think the apk file downloaded missing something that the apk found on the web have, but don't know what.

I used the python method with a Windows computer.

I really hope that it'll works at the and :)

Thanks in advance !

**Comment by ClaudiuGeorgiu** [comment]
Hi @Nicopotame, when downloading `com.adobe.reader` with my account I get a file of 551 MB that I can install successfully on Android 9 (haven't tried Android 11 yet). Maybe with your android id you're getting a different apk, please check the following:
- add the `-s` flag during download, do you get any additional file? I don't.
- look at the `lib/` folder inside the downloaded apk file, what directories do you see? In my case there are `x86_64`, `x86`, `armeabi-v7a` and `arm64-v8a`, do you see the same?

If your results are different than mine, then probably you are getting split apks with your android id, in such case with the `-s` flag you should get more than one file for each app and you should be able to install with `adb install-multiple <file1> <file2> ...` command. I haven't tried, so I'm not 100% sure it will work.

**Comment by Nicopotame** [comment]
Hi @ClaudiuGeorgiu ,

Thanks for your answer !

I'll try it when I'll be back home(tuesday).

Do you think it'll be better to link another device to get single apk files that I could install on any device easily after ?

And do you think the split apk could be install directly on the Android device ?
I'm most familiar with singles apk files ^^

I'll answer your questions asap !

Thanks a lot for your help !

**Comment by Nicopotame** [comment]
Hi @ClaudiuGeorgiu,

All apks are split as you said.
I'll be able to installed them with the adb command, thank you very much !

If anybody knows how to merge a split apk, I'd be happy to hear how do you do.

Kind regards,
