### ISSUE TITLE
WebDownloader not working

### ISSUE THREAD

**Issue by Kim123LP** [ClaudiuGeorgiu/PlaystoreDownloader#72]
### Screenshot
![image](https://user-images.githubusercontent.com/40537673/146687463-295e9a35-ac86-4434-91ef-e147b4957219.png)

### Details
**Installation mode** (e.g., from source or with Docker): Docker
**PlaystoreDownloader version** (e.g., commit c35f8bc): I dont know.
**OS** (e.g., Ubuntu 18.04): Windows 11
**Python version** (e.g., 3.8.6): 3.10.0

### Error
```[ERROR][engineio.server][_log_error_once()] The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)```

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> googleplay -a com.rovio.baba
Title: Angry Birds 2
UploadDate: Dec 16, 2021
VersionString: 2.60.2
VersionCode: 25046968
NumDownloads: 213.379 M
Size: 76.134 MB
Offer: 0.00 USD
~~~

https://github.com/89z/googleplay
