### ISSUE TITLE
Download APK removed from Google Play

### ISSUE THREAD

**Issue by PendalF89** [ClaudiuGeorgiu/PlaystoreDownloader#74]
Hello there!
Is any way to download an old APK files from Google Play, that were removed officially from Google Play?
For example: com.herogame.gplay.theoutlived
Google Play: https://play.google.com/store/apps/details?id=com.herogame.gplay.theoutlived
APK.support: https://apk.support/app/com.herogame.gplay.theoutlived

I don't believe, that APK.Support keeps all old APK files on their own servers. So, i think, that is possible to download old APK files from Google Play. But, how to do this?

**Comment by ClaudiuGeorgiu** [comment]
Hi @PendalF89, I actually never tried to download applications that are not available anymore from the Play Store, so I'm not 100% sure, but I believe that's not possible.

**Comment by david-lev** [comment]
Hi @PendalF89
Specifically on the app you sent, it is indeed stored on a server that does not belong to Google Play as seen in the following image:
![Screenshot_20211228-221132_Chrome.jpg](https://user-images.githubusercontent.com/42866208/147603570-217aff6d-1bf4-469f-aa4b-dfb9cf568377.jpg)
But in general, it's possible that when Google Play removes an app, they don't delete the files from their servers, and so - if you have a direct link to the apk file (play.playstoreapi.com), it may well continue to work even after Google Play removes the app from the Store.

**Comment by PendalF89** [comment]
Thank you for your replies guys!
I was doing an experiment with direct links to Google Play, for example: 
`https://play.googleapis.com/download/by-token/download?token=...`
redirects to:
`https://some-secret-site.com/play-apps-download-default/download/by-id/...`
Unfortunately, these links live for about 2 days, but they also have some get parameters that can affect the lifetime of links. I saved several such links today and want to check in a few days if I can get a file from them by changing the get parameters.

**Comment by david-lev** [comment]
> 

This [link](https://play.playstoreapi.com/index.php?token=7b2744fd64e51ac1614628f06d6539565c3da1a24bfdd7a6ac16d722c032a73f016ad7c7fd92ad988dab84033e80110ed1291828d42a331369f947d403bb80cb0c043b84ca074a5e02601e8bcdf1dd484f6017fd70243941d1936ecd34762bbbba9653417b5603d2d8fce6032396de093e927e54321af1a5372c4615c254f85dad3fae0c3d62c70636a62639616bc9988f5be81c734309036a1f2486f5b16059e786e895b34bff19f8ca7207421fb7853f0d450361e6b648536278c3a5ac911f93d2894cc7026e6d2f4ee4077dbe0adfa443dfe410a7fa2c386707594564ab903eb173bde008fc209076d4e5d4698a79430cc18b6f9aae93cb95adadfc235bc1f84117d723780de93fc0914ca103773851d3362b1a0f916c1c5540fbd052fd5332eb23819c695b91d745bcab1a40c227a1d2c8ef9c7356d62397ed86f035f35df9297d291622e72cadde1a64f3777824fbf933b8fd08b04c0b8f435038f02f15b7e391b5eb74c306a45180971a65b6e919d80905518a671aa96d0f392f42be15d455c1ea3db11d378d6c3a55cfa59854bd9a97385c3c6aca2c07dcae913d66041b06c4296796f46e89a03a20f7ef60bdc8a7aa6b5766c94a8130a2eb718f2e94d8f0f6e76c63fec527d5095ceca95600ad2f278fda263c541abdfe4b7ee59324f1d6a873d62a74fd05d1f3cf5015f5ec0d547aaa4e17062cabb9cd47f6d759f92307fc06f0bdae2d165a01efc05c98a692d8ff59d684d987988a97c5829f5583578235cc24fc8bd6979f0e3ed5f370425c2179f6943187516fe82a6a9f31e694ea) is from two weeks ago and still works

**Comment by PendalF89** [comment]
> 

But, it is not Google domain: https://www.whois.com/whois/playstoreapi.com
I also thought at first that these were links from Google Play, but no, this domain does not belong to Google.
Unfortunately, your link is not starting download for me.

**Comment by david-lev** [comment]
I do not know the name of the domain registered but I get the download link after I perform mitm on Google Play.
![image](https://user-images.githubusercontent.com/42866208/147607599-8990ea9f-9be0-4317-b38d-5d9ebed8c7e9.png)
And why does the link not work for you? I do not know. I tried to download from several devices that are not connected to the same network and in all of them the application downloads ..
This may be a location limitation or other similar limitation.

**Comment by PendalF89** [comment]
>Try to download from the [actual](https://r5---sn-oxu8pnpvo-ua8z.gvt1.com/play-apps-download-default/download/by-id/AF3DWBd7LwDQllXqLHZ9mV1neECTaHdex7BD5zYfVzoAh6jDxTAtzunxT8671fQAZvsfE62L64s4M22eGHwzdKSiTYHTBnqhc5RdF9cfY8EKUOSMeP4bn1Zi1jMnOgOYX8Tvosj794zxkByMHnbHJJuMKmI4p7xdoIh6iC1cwO6FY-mo__UKZD4?cpn=EpQSfITpekaNHZfM&ctier=L&initcwndbps=7640&mh=Sr&mm=31&mn=sn-oxu8pnpvo-ua8z&ms=au&mt=1640728871&mv=m&mvi=5&pl=47&expire=1640902058&ip=2a02:14f:1fe:46c4:4a:d564:27a:cc7f&ipbits=0&sparams=expire,ipbits,ip,q:,initcwndbps,mh,mm,mn,ms,mv,mvi,pl,ctier&signature=254D658B89B59B670F950E090F8A28FC6CED6EBA.76BA0476E58E0F77B025D64AF27BDFBF5D3C3827&key=am3) link.

This link works fine! How many days is this link?

**Comment by 89z** [comment]
Why does it matter how long the link lasts? Just generate a valid link, and download right away. If youre wanting to host the links on your own site, thats not going to work. Same with YouTube video links, or links from many other sites. You'll either need to generate a valid link on request, or download and rehost the actual APKs

**Comment by alanjsebas** [comment]
@david-lev What site is that and how are you obtaining the links?

**Comment by 89z** [comment]
@alanjsebas its from the Google API:

https://github.com/89z/googleplay/blob/v1.6.9/auth.go#L52-L87

**Comment by david-lev** [comment]
> @david-lev What site is that and how are you obtaining the links?

@alanjsebas The site I used before is https://apk.support/apk-downloader
But they started pulling files from other sites, too, so pay attention to the storage address of the apk file before you download.
