### ISSUE TITLE
Let client download the apk

### ISSUE THREAD

**Issue by RainerZufall187** [ClaudiuGeorgiu/PlaystoreDownloader#78]
Is it possible to read the APK download link from the Google API with Protobuf, which can then be downloaded by anyone without cookies and without an IP restriction? So my website can save a lot of bandwidth and it's faster anyway. I also saw a url from google somewhere where I could just download an apk like that.

**Comment by 89z** [comment]
Yes, here is one for `com.vimeo.android.videoapp`:

https://play.googleapis.com/download/by-token/download?token=AOTCm0SOJChGuJiekslN7druT4nshULyWBX5CzTZfntP-iR75fNt7QUGAFVD3dX9Li0HsR7sWFozgdc81ex3KsOfeDWi4yMpIFounxQyKpa0ih4B9zBlCkUdCUUEd5YTm9nWFisXJWH6JNtDow6TFcAfRehDnhD5EWfMruprQlumpXAIUbsReKhGwD1EpXJPwLj-PcG2yCHVIAUuYAqxolF58uek7YV08VkIfr7ZLqyvdI9wbnJwZF_HD2GI99nPtyDR1KKp409RYrYJerMbFT-8aTAkhAA1lul9NwfOb6Ja4JPzN2alXWaiH-ZmBTgcRudICYJbWi5Z98MPWoWIqVwJDTRxJl7a6K4sWXIricxdstXsmw76-YtdzUVJifmRG3GvRx0fCn3MNmkzvKbSRStz_8ljTstq2J86lVGy00g

However I believe the URL expires after some amount of time.
