### ISSUE TITLE
download free app  "Google Play purchases are not supported in your country"

### ISSUE THREAD

**Issue by mrjk990** [ClaudiuGeorgiu/PlaystoreDownloader#8]
`root@server:/var/www/html/PlaystoreDownloader# python3 download.py "com.facebook.lite"
03/11/2017 04:08:59> [ERROR][download()] Error for app "com.facebook.lite": Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.
Error when downloading "com.facebook.lite".`

is this error depends on credentials.json or google account country ?

**Comment by ClaudiuGeorgiu** [comment]
I think it depends on both, see #2 for more details. By the way, I'm in Italy with an Italian account and I'm able to download `com.facebook.lite`, maybe try using a VPN (I never tried this, so let me know if you manage to make it work).

**Comment by mrjk990** [comment]
hi
the problem depends on android version !!
i try download  "com.facebook.lite" with another google account , android version 4.4 it's work fine 
`root@server:/var/www/html/PlaystoreDownloader# python3 download.py "com.facebook.lite" -c credentials_mjk.json
Downloading com.facebook.lite: 1817 KB [00:00, 8863.31 KB/s]`
