### ISSUE TITLE
Login failed, please check your credentials (retrying in 1s)

### ISSUE THREAD

**Issue by kotko** [ClaudiuGeorgiu/PlaystoreDownloader#80]
Hi i get this error 
```
13/05/2022 10:30:51> [WARNING][playstoredownloader.playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
```

2 day ago all worked

**Comment by cuongtobi** [comment]
I got the same error

**Comment by kotko** [comment]
> 

Yes, So do I. but i get an error

**Comment by kotko** [comment]
> I got the same error, I use app password

So do I. but i get an error

**Comment by Arshit007** [comment]
I am not able to login in the playstore.It is giving me 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password' again and again

**Comment by ashutoshtiwari199** [comment]
I am also getting the same error, I tried with different id & appPassword but issue is still same...

> raise RuntimeError("Login failed, please check your credentials")
RuntimeError: Login failed, please check your credentials

**Comment by Croodo** [comment]
This is happening coz google is blocking the login, whenever I run command to download apk i get a google notification of google service about "Someone else used your Google password" "Google blocked this sign-in attempt, .........".

We have to find a solution to bypass google security (with logged device IP or something else I don't know ).

**Comment by kotko** [comment]
> I am not able to login in the playstore.It is giving me 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password' again and again

Does not help. tried everything

**Comment by alex-leader** [comment]
[WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 1s)
[WARNING][playstore.util][wrapped()] Login failed, please check your credentials (retrying in 2s)

What is the solution to this problem?
