### ISSUE TITLE
Login Failed |  App Password No Longer Works

### ISSUE THREAD

**Issue by msebastian100** [ClaudiuGeorgiu/PlaystoreDownloader#83]
Hello,
Unfortunately the login fails despite correct login data

App Password No Longer Works
"To better protect your account, from 30 May 2022, Google will no longer support third-party apps or devices where your username and password are sufficient to sign in to your Google Account."

Greetings Sebastian

**Comment by mkamranmazhar** [comment]
Login failed, please check your credentials (no more retries).
any solutions please ?

**Comment by hycwk** [comment]
so the application is not working now?
