### ISSUE TITLE
1111

### ISSUE THREAD

**Issue by zoujiangtao159** [ClaudiuGeorgiu/PlaystoreDownloader#9]

**Comment by zoujiangtao159** [comment]
I need to download Google Apps from different countries

**Comment by ClaudiuGeorgiu** [comment]
Hi, this is a known limitation (see #2 and #8). If you are not able to download an app directly using your phone, you won't be able to download that app by using this tool.

**Comment by zoujiangtao159** [comment]
This tool can not download a lot of applications, as a crawler, account, there will be a mobile google account to re-login
